# Generated by Django 5.1.4 on 2025-01-19 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Enter the payment date", verbose_name="payment date"
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the payment amount",
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="payment amount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "cash"), ("bank_transfer", "bank transfer")],
                        help_text="Choose the payment method",
                        max_length=13,
                        verbose_name="payment_method",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the course",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the lesson",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="courses.lesson",
                        verbose_name="lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the user",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
    ]
