# Generated by Django 5.1.4 on 2025-01-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Enter your course title", max_length=150, verbose_name="course title"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your course preview",
                        null=True,
                        upload_to="courses/course_preview",
                        verbose_name="course preview",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter your course description",
                        null=True,
                        verbose_name="course description",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Enter your lesson title", max_length=150, verbose_name="lesson title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter your lesson description",
                        null=True,
                        verbose_name="lesson description",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your lesson preview",
                        null=True,
                        upload_to="courses/lesson_preview",
                        verbose_name="lesson preview",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Enter your lesson video link",
                        null=True,
                        verbose_name="lesson video link",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the course",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
            },
        ),
    ]
